name: New Quote
description: Add a new quote to the collection
title: "[QUOTE] "
labels: ["quote"]
assignees:
  - asdf8601
body:
  - type: markdown
    attributes:
      value: |
        Add a new quote to the collection. Only @asdf8601 can create quotes via issues.
  
  - type: input
    id: author
    attributes:
      label: Author
      description: Who said or wrote this?
      placeholder: "Jorge Luis Borges"
    validations:
      required: true
  
  - type: input
    id: source
    attributes:
      label: Source
      description: Where is this quote from?
      placeholder: "Labyrinths"
    validations:
      required: true
  
  - type: textarea
    id: content
    attributes:
      label: Quote
      description: The actual quote text
      placeholder: "I have always imagined that Paradise will be a kind of library."
    validations:
      required: true
