name: New Content
description: Create new content (post, TIL, quote, or page)
title: "[CONTENT] "
labels: ["content"]
assignees:
  - asdf8601
body:
  - type: markdown
    attributes:
      value: |
        Write the complete file content below. When ready, comment `/mkdir <path>` to create the file.
        
        Examples:
        - `/mkdir src/pages/posts/my-post.mdx`
        - `/mkdir src/pages/til/grep-tips.md`
        - `/mkdir src/pages/quotes/borges.md`
  
  - type: textarea
    id: content
    attributes:
      label: Content
      description: Complete file content including frontmatter
      placeholder: |
        ---
        title: My Content
        date: 2025-10-31
        tag: example
        category: demo
        ---
        
        # My Content
        
        Your content here...
      render: markdown
    validations:
      required: true
