name: New Quote
description: Add a new quote to the collection
title: "[QUOTE] "
labels: ["quote"]
assignees:
  - asdf8601
body:
  - type: markdown
    attributes:
      value: |
        Write the complete markdown content below. When ready, comment `/quote filename` to create the file.
        
        Example: `/quote borges-library` will create `src/pages/quotes/borges-library.md`
  
  - type: textarea
    id: content
    attributes:
      label: Quote Content (Markdown)
      description: Complete markdown file content including frontmatter
      placeholder: |
        ---
        date: 2025-10-31
        author: Jorge Luis Borges
        source: Labyrinths
        ---
        
        I have always imagined that Paradise will be a kind of library.
      render: markdown
    validations:
      required: true
