name: New Post
description: Create a new blog post
title: "[POST] "
labels: ["post"]
assignees:
  - asdf8601
body:
  - type: markdown
    attributes:
      value: |
        Write the complete MDX content below. When ready, comment `/post filename` to create the file.
        
        Example: `/post my-awesome-post` will create `src/pages/posts/my-awesome-post.mdx`
  
  - type: textarea
    id: content
    attributes:
      label: Post Content (MDX)
      description: Complete MDX file content including frontmatter
      placeholder: |
        ---
        title: My Awesome Post
        date: 2025-10-31
        tag: python
        category: programming
        ---
        
        # My Awesome Post
        
        Your content here...
      render: markdown
    validations:
      required: true
